### ISSUE TITLE
http://spark-kubernetes/ is not working

### ISSUE THREAD

**Issue by anaidv57** [testdrivenio/spark-kubernetes#4]
Hi, 

I am following the steps that you have here: https://testdriven.io/blog/deploying-spark-on-kubernetes/ 

Thank you so much for sharing this with us.

I am having some problems. The test part is working, but this  http://spark-kubernetes/ doesn't work for me.
![etc_hosts](https://user-images.githubusercontent.com/31296172/64627122-f9e53e00-d3e6-11e9-9df1-d0e9ce3511f7.png)

when I execute minikube ip I get this: 192.168.99.103

Do you know another way to reach the same page (spark master)?

Kind regards, 
Anaid

**Comment by debuggerrr** [comment]
@anaidv57 Can you help me to start with the deployment of docker images and spark master? I am new to this and unable to do this. I was able to launch Kubernetes dashboard. Can you guide me over here pls?
